travis:
  secure:
    BINSTAR_TOKEN: UEVjlVdJx3uOuMw2Mtfm9f5H/wrFoBUCVCmctSjP4IdNn5M2w03oKjehCFbGPpC4bTpW5Q9J5X2W5RwPvD8Q2mN891jkxTC2gDRinQywJJdFnsu9DqGtzzBkUiL9rIEugb0Az8zuBTIMQv2ZuiMAS2w+ImYcnzkEDLxS+EtzQVjqHohKZhYxI4UbmmCB5gGvNPUjyQ6FPY9s/oeh9fhBF837EgsUcui5bAwkNdLtidJxwuAcPwPQFVQch4W7o7lzvjPck/0IstKVQe0CvFXfySC2yGwCHnRhCLu2W5Zu8BDnGTe1cmg9x/qbXnc8zQLyQ18AYjZdCeRQwQqw/jbT+R3bJrWILnipu5vfq6UGY3Hc6VsCz4AkAw0F3Ii5Bbo72/dp4f2rKbk8iVy9vDXac9gnZnkPB98oOJR3yMK66Tr06j0WlE/YDSf3UACoAqRh2WsV6Aa215VfeBtYiuSxrgpYBuGqB0W/S6rD/NhJz7tv6idFhfk6agpJ6xL0PibfHxn3HC+ixJ+n2vL+z3XghIdZbsnsAuXvnVt7qqgGushx70xCNiRgUcn2gs+JoYr5NGe44Bt+8g4zsw5GUfIQiYMRPdX4uBu8o+o+WkMg1xbamcUKfKwlyK1N3rwJ3FBP6pw9UBV1RJaOu4W0ZQWa7KffY+SnF781n/7Kmh0wrNE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
